import { useEffect, useMemo, useRef, useState, useSyncExternalStore } from 'react';
import { Activity, ArrowDown, ArrowDownToLine, ArrowRight, ArrowUpRight, Bell, BookOpen, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Command, FlaskConical, Globe2, LayoutDashboard, Layers3, Menu, MoreHorizontal, Plus, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrendingUp, Users, X, Zap, Code2, Server, GitBranch, CalendarDays, RefreshCw, CircleAlert, PanelLeftClose, FileChartColumn, Cable } from 'lucide-react';
import { Area, CartesianGrid, ComposedChart, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { initialExperiments, num, typeLabels, statusLabels, validTransition, downloadCSV } from './data';
import type { Experiment, ExperimentStatus, ExperimentType } from './data';
import { normalizeExperiments, findAvailableBucketRanges, validateAllocation, validateTopology, globalTraffic, getTopology, getTopologyLoadError, subscribeTopology } from './traffic';
import CreateExperiment from './components/CreateExperiment';
import { parseExperimentDraftRoute, newExperimentHref, experimentDraftHref } from './experiment-draft-routes';
import { listExperimentDrafts, DRAFT_CHANGED_EVENT, DRAFT_PREFIX, canLeaveExperimentDraft } from './experiment-drafts';
import { validateDraftForm } from './experiment-draft-validation';
import ExperimentDetail from './components/ExperimentDetail';
import ManagementPages from './components/ManagementPages';
import { experimentServices, getCatalog, getParameterService } from './service-catalog';
import { APPLICATION_ROUTE_CHANGE_EVENT, canonicalApplicationRoute } from './application-routes';
import { parseExperimentDestination } from './audience-reference-routes';
import { getAudiences } from './audiences';
import { experimentAudienceListHref, filterExperimentsByAudience, parseExperimentAudienceFilter } from './experiment-audience-filter';
import './components/experiment-audience-filter.css';

export const NAV = [
 {id:'overview',label:'实验总览',icon:LayoutDashboard}, {id:'experiments',label:'实验管理',icon:FlaskConical},
 {id:'traffic',label:'层域管理',icon:GitBranch}, {id:'applications',label:'应用管理',icon:Server}, {id:'metrics',label:'指标中心',icon:Activity},
 {id:'audiences',label:'受众管理',icon:Users}, {id:'reports',label:'实验报告',icon:FileChartColumn},
 {id:'integrations',label:'集成与 SDK',icon:Cable}, {id:'team',label:'团队与权限',icon:ShieldCheck}
];
function canonicalRoute(){return canonicalApplicationRoute(location.hash,getTopology());}
const STORAGE_KEY='exp-lab-experiments-v3';
function readSaved():Experiment[]{
 try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem('exp-lab-experiments-v2')||localStorage.getItem('exp-lab-experiments-v1')||'null');
 if(!Array.isArray(data)||!data.every(x=>x?.id&&x?.name&&Array.isArray(x.variants)&&Array.isArray(x.activities)&&x.status in statusLabels&&x.type in typeLabels))return initialExperiments;
 const migrated=normalizeExperiments(data);
 return [...migrated,...initialExperiments.filter(e=>(e.domainId==='exclusive'||e.id.startsWith('EXP-12'))&&!migrated.some(x=>x.id===e.id))];
 }catch{return initialExperiments}
}
const serviceNames=(e:Experiment)=>experimentServices(e,getTopology()).map(service=>service.name).join('、')||'待归属应用';
function ServicesBadge({experiment}:{experiment:Experiment}){const services=experimentServices(experiment,getTopology());return <span className="service-badge" title={serviceNames(experiment)}><Server size={13}/>{services.length===0?'待归属':services.length===1?services[0].name:`${services.length} 个应用`}</span>}
const typeIcons={frontend:Code2,backend:Server,strategy:SlidersHorizontal};
export function TypeBadge({type}:{type:ExperimentType}){const Icon=typeIcons[type];return <span className={`type-badge ${type}`}><Icon size={13}/>{typeLabels[type]}</span>}
export function StatusBadge({status}:{status:ExperimentStatus}){return <span className={`status-badge ${status}`}><span/>{statusLabels[status]}</span>}
function Sparkline({values,color}:{values:number[];color:string}){const d=values.map((v,i)=>`${i===0?'M':'L'} ${i*9} ${42-v}`).join(' ');return <svg className="sparkline" viewBox="0 0 100 46" aria-hidden="true"><path d={`${d} L 99 46 L 0 46 Z`} fill={color} opacity=".08"/><path d={d} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}

export default function App(){
 const topology=useSyncExternalStore(subscribeTopology,getTopology,getTopology);
 const topologyLoadError=getTopologyLoadError();
 const [experiments,setExperiments]=useState<Experiment[]>(readSaved);
 const [page,setPage]=useState(()=>canonicalRoute().split('?')[0].slice(1).split('/')[0]||'overview');
 const [selected,setSelected]=useState<string|null>(()=>parseExperimentDestination(location.hash).id);
 const [experimentRouteError,setExperimentRouteError]=useState<string|null>(()=>parseExperimentDestination(location.hash).error);
 const [draftRoute,setDraftRoute]=useState(()=>parseExperimentDraftRoute(location.hash));
 const [draftList,setDraftList]=useState(()=>listExperimentDrafts());
 const [sidebar,setSidebar]=useState(false),[notice,setNotice]=useState(false),[guide,setGuide]=useState(false);
 const [toast,setToast]=useState(''),[query,setQuery]=useState(''),[globalSearch,setGlobalSearch]=useState(false),[statusFilter,setStatusFilter]=useState('all');
 const [period,setPeriod]=useState(14),[lastSync,setLastSync]=useState('14:32');
 const mainRef=useRef<HTMLElement>(null);
 const loadedTopology=useRef<string|null>(null);
 useEffect(()=>{try{loadedTopology.current=localStorage.getItem('exp-lab-topology-v1');}catch{/* Submit reports storage failures. */}},[topology]);
 const previousRoute=useRef(location.hash), listReturnRoute=useRef('#experiments');
 useEffect(()=>{const onHash=()=>{
  const route=canonicalRoute();
  if(route!==previousRoute.current&&!canLeaveExperimentDraft()){history.replaceState(null,'',previousRoute.current);return;}
  const changed=route!==location.hash;if(changed)history.replaceState(null,'',route);
  const [p]=route.split('?')[0].slice(1).split('/'),draft=parseExperimentDraftRoute(route),destination=parseExperimentDestination(route);
  const previousPage=previousRoute.current.split('?')[0].replace(/^#/,'').split('/')[0];
  if(p==='experiments'&&draft.kind==='none'&&!destination.id&&!destination.error&&route.split('?')[0]==='#experiments'){
   listReturnRoute.current=route;
   if(previousPage!=='experiments'){const filter=parseExperimentAudienceFilter(route);if(filter.audienceId||filter.error){setQuery('');setStatusFilter('all');}mainRef.current?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}
  }
  previousRoute.current=route;setPage(NAV.some(n=>n.id===p)?p:'overview');setDraftRoute(draft);
  setSelected(p==='experiments'&&draft.kind==='none'?destination.id:null);setExperimentRouteError(p==='experiments'&&draft.kind==='none'?destination.error:null);
  if(changed)window.dispatchEvent(new Event(APPLICATION_ROUTE_CHANGE_EVENT));
 };window.addEventListener('hashchange',onHash);onHash();return()=>window.removeEventListener('hashchange',onHash)},[topology]);
 useEffect(()=>{const refresh=()=>setDraftList(listExperimentDrafts());const external=(event:StorageEvent)=>{if(event.key?.startsWith(DRAFT_PREFIX)||event.key===null)refresh();if(event.key===STORAGE_KEY)setExperiments(readSaved());};window.addEventListener(DRAFT_CHANGED_EVENT,refresh);window.addEventListener('storage',external);return()=>{window.removeEventListener(DRAFT_CHANGED_EVENT,refresh);window.removeEventListener('storage',external);};},[]);
 useEffect(()=>{if(topologyLoadError)return;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(experiments))}catch{setToast('浏览器存储不可用，本次修改仅在当前页面保留。')}},[experiments,topologyLoadError]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)}},[toast]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setGlobalSearch(v=>!v)}if(e.key==='Escape'){setNotice(false);setGuide(false);setGlobalSearch(false);setSidebar(false)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{if(!globalSearch&&!guide)return;const dialog=document.querySelector<HTMLElement>(guide?'.guide-modal':'.command-dialog');const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog?.querySelector<HTMLElement>('input,button')?.focus();const trap=(e:KeyboardEvent)=>{if(e.key!=='Tab')return;const items=Array.from(dialog?.querySelectorAll<HTMLElement>('button:not(:disabled),input,select,[tabindex="0"]')||[]).filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};document.addEventListener('keydown',trap);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',trap);previous?.focus()}},[guide,globalSearch]);
 const navigate=(p:string)=>{if(!canLeaveExperimentDraft())return;location.hash=p;setPage(p.replace(/^#/,'').split('?')[0].split('/')[0]);setSelected(null);setSidebar(false);setGlobalSearch(false);setNotice(false);mainRef.current?.focus();window.scrollTo({top:0,behavior:'instant'})};
 const openDetail=(e:Experiment)=>{if(!canLeaveExperimentDraft())return;listReturnRoute.current=page==='experiments'&&!selected&&!experimentRouteError&&location.hash.split('?')[0]==='#experiments'?location.hash:'#experiments';setSelected(e.id);setExperimentRouteError(null);setPage('experiments');location.hash=`experiments/${encodeURIComponent(e.id)}`;mainRef.current?.focus();window.scrollTo({top:0,behavior:'smooth'})};
 const startCreate=()=>navigate(newExperimentHref());
 const draftReady=(id:string)=>{const href=experimentDraftHref(id);history.replaceState(null,'',href);previousRoute.current=href;setDraftRoute({kind:'draft',draftId:id});setSelected(null);setExperimentRouteError(null);};
 const createFromDraft=(candidate:Experiment):string|{experimentId:string}=>{
  try{if(localStorage.getItem('exp-lab-topology-v1')!==loadedTopology.current)return '层域或应用配置已在其他页面更新。草稿已保存，请刷新后重新检查并提交。';const raw=localStorage.getItem(STORAGE_KEY);if(raw){const saved=JSON.parse(raw);if(!Array.isArray(saved)||!saved.every(e=>e?.id&&e?.name&&Array.isArray(e.variants)&&Array.isArray(e.activities)&&e.status in statusLabels&&e.type in typeLabels))return '实验列表数据无法读取，提交已暂停，原始内容已保留。';}}catch{return '无法读取最新实验配置，提交已暂停，草稿仍保留。';}
  const fresh=readSaved();
  const duplicate=fresh.find(e=>e.sourceDraftId&&e.sourceDraftId===candidate.sourceDraftId);
  if(duplicate){setExperiments(fresh);openDetail(duplicate);return {experimentId:duplicate.id};}
  if(fresh.some(e=>e.id===candidate.id)){setExperiments(fresh);return '实验列表已更新，请再次提交；当前草稿已保存。';}
  const issues=validateDraftForm({name:candidate.name,key:candidate.key,description:candidate.description,hypothesis:candidate.hypothesis??'',domainId:candidate.domainId,layerId:candidate.layerId,traffic:candidate.traffic,audienceId:candidate.audienceId??'',metric:candidate.metric,guardrails:candidate.guardrails??[],variants:candidate.variants as import('./variant-draft-operations').DraftExperimentVariant[]},fresh,getTopology());
  if(issues.length){setExperiments(fresh);return issues[0].message;}
  const ranges=findAvailableBucketRanges(candidate.layerId,candidate.traffic,fresh,undefined,getTopology(),candidate);
  if(!ranges?.length)return '当前可用流量已变化，请重新检查。';
  const experiment={...candidate,bucketRanges:ranges,bucketStart:ranges[0].start/100};
  const invalid=validateAllocation(experiment,fresh,getTopology());if(invalid)return invalid;
  const next=[experiment,...fresh];try{localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}catch{return '实验尚未提交：浏览器存储不可用或容量不足，草稿仍保留。';}
  setExperiments(next);openDetail(experiment);setToast('已提交审核并预留流量，审核通过后可启动实验');return {experimentId:experiment.id};
 };
 const changeStatus=(id:string,status:ExperimentStatus)=>{
  const e=experiments.find(x=>x.id===id);
  if(!e||!validTransition(e.status,status)){setToast('当前状态不支持此操作');return}
  let candidate={...e,status};
  if(status==='review'){
   const currentConfigError=validateTopology(getTopology(),experiments);
   if(currentConfigError){setToast(currentConfigError);return}
   const bucketRanges=findAvailableBucketRanges(e.layerId,e.traffic,experiments,id,getTopology(),{audienceId:e.audienceId,audience:e.audience});
   if(bucketRanges===null){setToast('当前受众下可用桶总量不足，无法提交审核。请调整申请流量或受众条件。');return}
   candidate={...candidate,bucketStart:bucketRanges[0].start/100,bucketRanges};
  }
  if(['review','running'].includes(status)){
   const invalid=validateAllocation(candidate,experiments);
   if(invalid){setToast(invalid);return}
  }
  const title=status==='review'?'提交实验审核并预留流量':status==='running'?(e.status==='review'?'演示审核通过，启动实验':'恢复实验'):status==='paused'?'暂停实验，保留原桶区间':status==='completed'?'停止入组，等待结果成熟':'退回草稿，释放预留流量';
  setExperiments(prev=>prev.map(x=>x.id===id?{...candidate,activities:[...x.activities,{title,time:new Date().toLocaleString('sv-SE').slice(0,16),person:e.status==='review'?'演示审核人':'陈思远'}]}:x));setToast(title)
 };
 const current=draftRoute.kind==='none'?experiments.find(e=>e.id===selected):undefined;
 const editableDrafts=draftList.ok?draftList.drafts.filter(d=>!experiments.some(e=>e.sourceDraftId===d.id)):[];
 const reviewCount=experiments.filter(e=>e.status==='review').length;
 const warning=experiments.filter(e=>e.health==='warning'&&e.status==='running');
 const exportAll=()=>{downloadCSV('EXP-Lab-实验清单.csv',[['实验ID','实验名称','涉及应用','状态','域ID','参数层ID','域内计划流量(%)','全局名义流量(%)','参与用户','主指标','相对变化(%)'],...experiments.map(e=>[e.id,e.name,serviceNames(e),statusLabels[e.status],e.domainId,e.layerId,e.traffic,globalTraffic(e),e.participants,e.metric,e.lift??''])]);setToast('实验清单已导出')};
 const pageName=NAV.find(n=>n.id===page)?.label||'实验总览';
 if(topologyLoadError)return <main className="configuration-load-error" role="alert"><CircleAlert size={30}/><h1>暂时无法加载应用配置</h1><p>{topologyLoadError}</p><p>已有本地数据已保留。重新加载成功后可继续管理应用和实验。</p><button className="btn btn-primary" onClick={()=>window.location.reload()}><RefreshCw size={15}/>重新加载</button></main>;
 return <div className="app-shell">
  {sidebar&&<button className="sidebar-overlay" aria-label="关闭导航" onClick={()=>setSidebar(false)}/>}
  <aside className={`sidebar ${sidebar?'is-open':''}`}>
   <a className="brand" href="#overview" onClick={event=>{event.preventDefault();navigate('overview')}}><span className="brand-mark"><FlaskConical size={24}/><span className="brand-dot"/></span><span>EXP<span className="brand-light"> Lab</span></span><span className="brand-beta">企业版</span></a>
   <button className="workspace-switch" onClick={()=>navigate('team')}><span className="workspace-icon"><Layers3 size={19}/></span><span><strong>星云科技</strong><small>企业工作空间</small></span><ChevronDown size={15}/></button>
   <div className="nav-label">工作空间</div>
   <nav aria-label="主要导航">{NAV.slice(0,7).map(item=><button key={item.id} className={`nav-item ${page===item.id?'active':''}`} onClick={()=>{setQuery('');setStatusFilter('all');navigate(item.id)}} aria-current={page===item.id?'page':undefined}><item.icon size={18}/><span>{item.label}</span>{item.id==='experiments'&&<span className="nav-count">{experiments.length}</span>}</button>)}</nav>
   <div className="nav-label second">组织管理</div>
   <nav aria-label="组织管理">{NAV.slice(7).map(item=><button key={item.id} className={`nav-item ${page===item.id?'active':''}`} onClick={()=>navigate(item.id)} aria-current={page===item.id?'page':undefined}><item.icon size={18}/><span>{item.label}</span></button>)}</nav>
   <div className="sidebar-bottom"><button className="learning-card" onClick={()=>setGuide(true)}><span className="learning-symbol"><BookOpen size={19}/><ArrowUpRight size={16}/></span><strong>让实验更有价值</strong><span>探索团队的实验最佳实践</span><span className="learn-link">查看指南 <ArrowRight size={13}/></span></button><button className="sidebar-setting" onClick={()=>navigate('team')}><Settings2 size={17}/>工作空间设置</button><div className="sidebar-foot"><span><span className="online-dot"/>本地交互原型</span><PanelLeftClose size={15}/></div></div>
  </aside>
  <div className="main-shell">
   <header className="topbar"><div className="breadcrumb"><button className="icon-btn mobile-menu" onClick={()=>setSidebar(true)} aria-label="打开导航"><Menu size={20}/></button><span className="breadcrumb-home">工作空间</span><ChevronRight size={13}/><strong>{pageName}</strong>{current&&<><ChevronRight size={13}/><span>{current.id}</span></>}</div><div className="top-actions"><span className="environment-label"><span/>演示工作区</span><button className="top-search" onClick={()=>setGlobalSearch(v=>!v)} aria-label="全局搜索"><Search size={16}/><span>搜索</span><kbd>⌘ K</kbd></button><div className="top-divider"/><button className="icon-btn" onClick={()=>setGuide(true)} aria-label="帮助中心"><CircleHelp size={18}/></button><div className="notice-wrap"><button className="icon-btn bell-btn" onClick={()=>setNotice(v=>!v)} aria-label={`通知，${reviewCount+warning.length} 条待处理`} aria-expanded={notice}><Bell size={18}/>{(reviewCount+warning.length)>0&&<i/>}</button>{notice&&<div className="notification-popover"><div className="popover-title">通知中心<span>{reviewCount+warning.length} 条待处理</span></div>{warning.map(e=><button key={e.id} onClick={()=>{openDetail(e);setNotice(false)}}><CircleAlert size={18}/><span><strong>护栏指标波动</strong><small>{e.name} · 查看详情</small></span><ChevronRight size={15}/></button>)}{experiments.filter(e=>e.status==='review').map(e=><button key={e.id} onClick={()=>{openDetail(e);setNotice(false)}}><ShieldCheck size={18}/><span><strong>实验等待审核</strong><small>{e.name}</small></span><ChevronRight size={15}/></button>)}{reviewCount+warning.length===0&&<div className="empty-state">暂无待处理通知</div>}<div className="popover-foot">演示通知 · 随实验状态更新</div></div>}</div><button className="user-avatar" onClick={()=>navigate('team')} aria-label="陈思远的团队资料">陈</button></div></header>
   <main className="main-content" ref={mainRef} tabIndex={-1}>
    {page==='experiments'&&draftRoute.kind!=='none'?(draftRoute.kind==='invalid'?<section className="card ew-load-error" role="alert"><h1>无法打开实验草稿</h1><p>{draftRoute.error}</p><button className="btn" onClick={()=>navigate('experiments')}>返回实验列表</button></section>:<CreateExperiment key={draftRoute.kind==='draft'?draftRoute.draftId:`new-${draftRoute.initialLayerId??draftRoute.copyExperimentId??'blank'}`} existing={experiments} draftId={draftRoute.kind==='draft'?draftRoute.draftId:undefined} initialLayerId={draftRoute.kind==='new'?draftRoute.initialLayerId:undefined} copyExperimentId={draftRoute.kind==='new'?draftRoute.copyExperimentId:undefined} onDraftReady={draftReady} onClose={()=>navigate(listReturnRoute.current)} onCreate={createFromDraft}/>):page==='experiments'&&(experimentRouteError||(selected&&!current))?<section className="card aud-not-found" role="alert"><CircleAlert size={22}/><div><h1>{experimentRouteError?'实验地址无效':'未找到实验'}</h1><p>{experimentRouteError??`当前工作空间不存在实验 ${selected}，没有跳转到其他实验。`}</p><button className="btn" onClick={()=>navigate('experiments')}>返回实验列表</button></div></section>:current?<ExperimentDetail key={current.id} experiment={current} onBack={()=>navigate(listReturnRoute.current)} onChangeStatus={changeStatus} notify={setToast}/>:page==='overview'?<>
     <div className="page-heading"><div><div className="eyebrow"><span/>EXPERIMENT WORKSPACE</div><h1>实验总览<span className="title-dot">.</span></h1><p>从一个好想法，到一次有依据的决策。</p></div><div className="heading-actions"><button className="btn" onClick={exportAll}><ArrowDownToLine size={16}/>导出报告</button><button className="btn btn-primary" onClick={startCreate}><Plus size={17}/>创建实验</button></div></div>
     <div className="dashboard-toolbar"><div className="workspace-tabs"><button className="selected">工作空间概况</button><button onClick={()=>{setQuery('');setStatusFilter('review');navigate('experiments')}}>待我处理 <span>{reviewCount}</span></button></div><div className="period-tools"><span className="sync-label"><span className="online-dot"/>更新于 {lastSync}</span><select aria-label="趋势时间范围" className="period-select" value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={7}>最近 7 天</option><option value={14}>最近 14 天</option><option value={30}>最近 30 天</option></select><button className="icon-btn refresh-btn" aria-label="刷新数据" onClick={()=>{setLastSync(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}));setToast('已刷新本地演示数据')}}><RefreshCw size={15}/></button></div></div>
     <OverviewStats experiments={experiments}/>
     <div className="analytics-grid"><TrendChart period={period}/><HealthPanel experiments={experiments} onOpen={openDetail} onReview={()=>{setStatusFilter('review');navigate('experiments')}}/></div>
     <ExperimentTable key="overview-experiment-list" experiments={experiments} query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} onOpen={openDetail} onCreate={startCreate} compact/>
     <div className="page-footer"><span>好实验，让增长有迹可循。</span><span>EXP Lab · 所有指标均为演示数据</span></div>
    </>:page==='experiments'?<><div className="page-heading simple"><div><h1>实验管理</h1><p>统一管理每一项实验，让协作与探索井然有序。</p></div><div className="heading-actions"><button className="btn" onClick={exportAll}><ArrowDownToLine size={16}/>导出清单</button><button className="btn btn-primary" onClick={startCreate}><Plus size={17}/>创建实验</button></div></div><div className="experiment-summary"><span>全部实验 <strong>{experiments.length}</strong></span><span><i className="running-dot"/>运行中 <strong>{experiments.filter(e=>e.status==='running').length}</strong></span><span><i className="review-dot"/>待审核 <strong>{reviewCount}</strong></span><span><CheckCheck size={15}/>已结束 <strong>{experiments.filter(e=>e.status==='completed').length}</strong></span></div>{(!draftList.ok||draftList.warnings.length>0)&&<p className="ew-action-error" role="alert">{draftList.ok?'部分本地草稿无法读取，原始内容已保留。':draftList.error}</p>}{editableDrafts.length>0&&<section className="ew-drafts" aria-label="本地实验草稿"><div className="ew-drafts-heading"><h2>编辑中的草稿 <span className="count-badge">{editableDrafts.length}</span></h2><span>仅当前浏览器 · 不预占流量</span></div><div className="ew-draft-list">{editableDrafts.map(d=><button key={d.id} className="ew-draft-card" onClick={()=>navigate(experimentDraftHref(d.id))}><span><strong>{d.form.name||'未命名实验'}</strong><small>{d.form.variants.length} 个分组 · {new Date(d.updatedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})} 保存</small></span><ArrowRight size={16}/></button>)}</div></section>}<ExperimentTable key="full-experiment-list" experiments={experiments} query={query} setQuery={setQuery} status={statusFilter} setStatus={setStatusFilter} onOpen={openDetail} onCreate={startCreate}/></>:<ManagementPages page={page} experiments={experiments} onOpen={openDetail} notify={setToast}/>}
   </main>
  </div>

  {toast&&<div className="toast" role="status"><span><Check size={16}/></span>{toast}<button aria-label="关闭提示" onClick={()=>setToast('')}><X size={15}/></button></div>}
  {globalSearch&&<div className="modal-overlay" onClick={()=>setGlobalSearch(false)}><div className="command-dialog" role="dialog" aria-modal="true" aria-label="搜索实验" onClick={e=>e.stopPropagation()}><div className="command-input"><Search size={20}/><input autoFocus value={query} placeholder="搜索实验名称、标识或负责人…" aria-label="全局搜索实验" onChange={e=>setQuery(e.target.value)}/><button className="icon-btn" onClick={()=>setGlobalSearch(false)} aria-label="关闭搜索"><X size={18}/></button></div><div className="command-results">{experiments.filter(e=>`${e.name} ${e.key} ${e.owner}`.toLowerCase().includes(query.toLowerCase())).slice(0,6).map(e=><button key={e.id} onClick={()=>{openDetail(e);setGlobalSearch(false)}}><FlaskConical size={17}/><span><strong>{e.name}</strong><small>{e.id} · {serviceNames(e)}</small></span><ArrowUpRight size={16}/></button>)}{!experiments.some(e=>`${e.name} ${e.key} ${e.owner}`.toLowerCase().includes(query.toLowerCase()))&&<div className="empty-state">没有找到匹配的实验，请尝试其他关键词。</div>}</div><div className="command-foot">搜索当前工作空间内的实验 <kbd>ESC 关闭</kbd></div></div></div>}
  {guide&&<Guide onClose={()=>setGuide(false)}/>}
 </div>
}

function OverviewStats({experiments}:{experiments:Experiment[]}){
 const running=experiments.filter(e=>e.status==='running');const total=experiments.reduce((s,e)=>s+e.participants,0);const wins=experiments.filter(e=>e.status==='completed'&&e.significant&&e.lift!==null&&e.lift>0).length;const needs=experiments.filter(e=>e.status==='review'||(e.status==='running'&&e.health==='warning')).length;
 const cards=[{label:'运行中实验',value:String(running.length).padStart(2,'0'),unit:'个',icon:FlaskConical,color:'green',trend:`覆盖 ${new Set(running.flatMap(e=>experimentServices(e,getTopology()).map(service=>service.id))).size} 个应用`,foot:'探索正在发生',values:[12,17,15,22,19,23,24,30,27,34,37,37]}, {label:'累计参与用户',value:(total/10000).toFixed(2),unit:'万',icon:Users,color:'blue',trend:'按实验去重后汇总',foot:'跨实验用户可能重叠',values:[8,10,8,14,17,15,20,24,27,26,33,38]}, {label:'正向结果实验',value:String(wins).padStart(2,'0'),unit:'个',icon:TrendingUp,color:'purple',trend:`已结束 ${experiments.filter(e=>e.status==='completed').length} 个实验`,foot:'演示结论 · 非上线建议',values:[11,11,16,16,21,19,25,25,30,30,35,38]}, {label:'需要关注',value:String(needs).padStart(2,'0'),unit:'项',icon:CircleAlert,color:'orange',trend:`${experiments.filter(e=>e.status==='review').length} 项审核 · ${experiments.filter(e=>e.status==='running'&&e.health==='warning').length} 项预警`,foot:'及时关注实验动态',values:[32,30,34,26,29,22,25,20,19,16,18,15]}];
 return <div className="stat-grid">{cards.map(c=><div className={`stat-card ${c.color}`} key={c.label}><div className="stat-top"><span>{c.label}</span><span className="stat-icon"><c.icon size={17}/></span></div><div className="stat-value">{c.value}<span>{c.unit}</span></div><div className="stat-bottom"><span><span className="stat-context">{c.trend}</span><small>{c.foot}</small></span><Sparkline values={c.values} color={c.color==='green'?'#288d64':c.color==='blue'?'#5d90bc':c.color==='purple'?'#9482bd':'#d3a464'}/></div></div>)} </div>
}

function TrendChart({period}:{period:number}){
 const [mode,setMode]=useState('participants'),[hidden,setHidden]=useState<string[]>([]);
 const data=useMemo(()=>Array.from({length:period},(_,i)=>{const d=new Date(2026,8,6-period+1+i);return {date:`${String(d.getMonth()+1).padStart(2,'0')}/${String(d.getDate()).padStart(2,'0')}`,frontend:Math.round((2.3+i*.15+Math.sin(i*1.2)*.3)*(mode==='participants'?10000:2)),backend:Math.round((1.2+i*.09+Math.cos(i*.7)*.17)*(mode==='participants'?10000:2)),strategy:Math.round((3.3+i*.21+Math.sin(i*.95)*.35)*(mode==='participants'?10000:2))}}),[period,mode]);
 const legend=[{key:'strategy',label:'排序参数层',color:'#3c8966'},{key:'frontend',label:'展示参数层',color:'#9dbe64'},{key:'backend',label:'交易参数层',color:'#85a8c4'}];
 return <section className="card trend-card"><div className="section-title"><div><h2>实验参与趋势</h2><span>观察流量变化，掌握实验节奏</span></div><div className="segmented small"><button className={mode==='participants'?'active':''} onClick={()=>setMode('participants')}>参与用户</button><button className={mode==='exposure'?'active':''} onClick={()=>setMode('exposure')}>运行实验</button></div></div><div className="chart-caption"><span>{mode==='participants'?'每日参与用户（万）':'每日运行实验（个）'} <span className="muted">· 示例趋势</span></span><div className="chart-legend">{legend.map(l=><button key={l.key} className={hidden.includes(l.key)?'is-muted':''} onClick={()=>setHidden(v=>v.includes(l.key)?v.filter(x=>x!==l.key):[...v,l.key])} aria-pressed={!hidden.includes(l.key)}><i style={{background:l.color}}/>{l.label}</button>)}</div></div><div className="trend-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{top:10,right:12,left:-22,bottom:0}} accessibilityLayer><defs><linearGradient id="greenArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8cbb77" stopOpacity={.2}/><stop offset="100%" stopColor="#8cbb77" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e9ede9" strokeDasharray="3 4"/><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{fill:'#909890',fontSize:10}} minTickGap={35} dy={8}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#909890',fontSize:10}} tickFormatter={v=>mode==='participants'?`${v/10000}`:`${v}`} tickCount={4}/><Tooltip contentStyle={{border:'1px solid #e6eae6',borderRadius:10,fontSize:12,boxShadow:'0 8px 30px #18372112'}} formatter={(v,n)=>[mode==='participants'?Number(v).toLocaleString('zh-CN')+' 人':v+' 个',legend.find(x=>x.key===n)?.label||n]} labelFormatter={v=>`${v} · 演示数据`}/><Area hide={hidden.includes('strategy')} type="monotone" dataKey="strategy" stroke="#3c8966" strokeWidth={2.3} fill="url(#greenArea)" activeDot={{r:4}} isAnimationActive={false}/><Line hide={hidden.includes('frontend')} type="monotone" dataKey="frontend" stroke="#9dbe64" strokeWidth={2} dot={false} strokeDasharray="5 3" isAnimationActive={false}/><Line hide={hidden.includes('backend')} type="monotone" dataKey="backend" stroke="#85a8c4" strokeWidth={2} dot={false} isAnimationActive={false}/></ComposedChart></ResponsiveContainer></div></section>
}

function HealthPanel({experiments,onOpen,onReview}:{experiments:Experiment[];onOpen:(e:Experiment)=>void;onReview:()=>void}){
 const running=experiments.filter(e=>e.status==='running'),healthy=running.filter(e=>e.health==='healthy').length;const ratio=running.length?Math.round(healthy/running.length*100):100;const warning=running.find(e=>e.health==='warning');const review=experiments.filter(e=>e.status==='review').length;
 return <section className="card health-card"><div className="section-title"><h2>实验健康度</h2><span className="live-tag"><span/>实时概况</span></div><div className="health-main"><div className="health-ring"><svg viewBox="0 0 108 108"><circle cx="54" cy="54" r="45" fill="none" stroke="#edf1ea" strokeWidth="8"/><circle cx="54" cy="54" r="45" fill="none" stroke="#b8d684" strokeWidth="8" strokeDasharray={`${ratio*2.827} 282.7`} strokeLinecap="round" transform="rotate(-90 54 54)"/></svg><div><strong>{ratio}<small>%</small></strong><span>运行正常</span></div></div><div className="health-description"><span className="health-state"><ShieldCheck size={15}/>{warning?'整体运行平稳':'所有实验正常'}</span><strong>{healthy}<small> / {running.length} 个运行中实验</small></strong><span className="muted">通过当前演示健康检查</span></div></div><div className="health-alerts">{warning?<button onClick={()=>onOpen(warning)}><span className="alert-icon amber"><Activity size={15}/></span><span><strong>1 个实验触发指标预警</strong><small>{warning.name}</small></span><ChevronRight size={15}/></button>:<div className="health-clear"><CheckCheck size={16}/>没有护栏指标预警</div>}<button onClick={onReview}><span className="alert-icon gray"><ShieldCheck size={15}/></span><span><strong>{review} 个实验等待审核</strong><small>审核通过后即可开始探索</small></span><ChevronRight size={15}/></button></div></section>
}

function ExperimentTable({experiments,query,setQuery,status,setStatus,onOpen,onCreate,compact=false}:{experiments:Experiment[];query:string;setQuery:(s:string)=>void;status:string;setStatus:(s:string)=>void;onOpen:(e:Experiment)=>void;onCreate:()=>void;compact?:boolean}){
 const [type,setType]=useState('all'),[mine,setMine]=useState(false),[page,setPage]=useState(1),[sort,setSort]=useState<'default'|'asc'|'desc'>('default');
 const size=compact?5:8;
 const [audienceFilter,setAudienceFilter]=useState(()=>compact?{audienceId:null,error:null}:parseExperimentAudienceFilter(location.hash));
 useEffect(()=>{if(compact)return;const sync=()=>{if(location.hash.split('?')[0]==='#experiments')setAudienceFilter(parseExperimentAudienceFilter(location.hash));};window.addEventListener('hashchange',sync);window.addEventListener(APPLICATION_ROUTE_CHANGE_EVENT,sync);sync();return()=>{window.removeEventListener('hashchange',sync);window.removeEventListener(APPLICATION_ROUTE_CHANGE_EVENT,sync);};},[compact]);
 useEffect(()=>setPage(1),[query,status,type,mine,sort,audienceFilter.audienceId,audienceFilter.error]);
 const audiences=getAudiences(getTopology()),selectedAudience=audiences.find(audience=>audience.id===audienceFilter.audienceId);
 const audienceError=audienceFilter.error??(audienceFilter.audienceId&&!selectedAudience?'所选受众版本不存在，请选择其他受众或清除筛选。':null);
 const changeAudience=(id:string)=>{setAudienceFilter({audienceId:id||null,error:null});setPage(1);location.hash=experimentAudienceListHref(id||undefined);};
 const clearFilters=()=>{setQuery('');setStatus('all');setType('all');setMine(false);if(!compact)changeAudience('');};
 const audienceExperiments=compact?experiments:audienceError?[]:filterExperimentsByAudience(experiments,audienceFilter.audienceId,getTopology());
 const filtered=audienceExperiments.filter(e=>(status==='all'||e.status===status)&&(type==='all'||experimentServices(e,getTopology()).some(service=>service.id===type))&&(!mine||e.owner==='陈思远')&&`${e.name} ${e.key} ${e.owner} ${e.id}`.toLowerCase().includes(query.toLowerCase()));
 if(sort!=='default')filtered.sort((a,b)=>sort==='desc'?b.participants-a.participants:a.participants-b.participants);
 const pages=Math.max(1,Math.ceil(filtered.length/size)),safePage=Math.min(page,pages);const visible=filtered.slice((safePage-1)*size,safePage*size);
 return <section className="card experiment-table-card"><div className="table-heading"><h2>{compact?'实验动态':audienceFilter.audienceId||audienceError?'受众关联实验':'全部实验'}<span className="count-badge">{audienceExperiments.length}</span></h2><label className="mine-filter"><input type="checkbox" checked={mine} onChange={e=>setMine(e.target.checked)}/>只看我负责的</label></div><div className="table-toolbar"><div className="table-tabs">{[['all','全部'],['running','运行中'],['review','待审核'],['completed','已结束']].map(([key,label])=><button key={key} className={status===key?'active':''} onClick={()=>setStatus(key)}>{label}<span>{key==='all'?audienceExperiments.length:audienceExperiments.filter(e=>e.status===key).length}</span></button>)}<select aria-label="更多实验状态" value={['draft','paused'].includes(status)?status:''} onChange={e=>setStatus(e.target.value||'all')}><option value="">更多状态</option><option value="draft">草稿</option><option value="paused">已暂停</option></select></div><div className="table-filters"><div className="search-field"><Search size={14}/><input aria-label="搜索实验" placeholder="搜索实验名称或 ID" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={13}/></button>}</div><select aria-label="涉及应用筛选" value={type} onChange={e=>setType(e.target.value)}><option value="all">全部服务</option>{getCatalog(getTopology()).services.map(service=><option key={service.id} value={service.id}>{service.name}</option>)}</select>{!compact&&<label className="experiment-audience-select"><Users size={14}/><select aria-label="受众筛选" value={audienceFilter.audienceId??''} onChange={event=>changeAudience(event.target.value)}><option value="">全部受众</option>{audienceFilter.audienceId&&!selectedAudience&&<option value={audienceFilter.audienceId}>不可用受众 · {audienceFilter.audienceId}</option>}{audiences.map(audience=><option key={audience.id} value={audience.id}>{audience.name} · v{audience.version}</option>)}</select></label>}</div></div>
 {!compact&&(audienceFilter.audienceId||audienceError)&&<div className={`experiment-audience-active ${audienceError?'has-error':''}`} role={audienceError?'alert':'status'}><Users size={15}/><div>{audienceError?<strong>{audienceError}</strong>:<><strong>受众：{selectedAudience?.name} · v{selectedAudience?.version}</strong><span>包含实验直接引用和从祖先域继承的实验，可继续叠加其他筛选。</span></>}</div><button className="btn btn-small" onClick={()=>changeAudience('')}><X size={12}/>清除受众筛选</button></div>}
 <div className="table-scroll"><table className="experiment-table"><thead><tr><th>实验名称</th><th>涉及应用</th><th>状态</th><th title="相对于所属域的计划流量；全局名义占比需乘域份额">域内计划流量 <CircleHelp size={11}/></th><th aria-sort={sort==='asc'?'ascending':sort==='desc'?'descending':'none'}><button className="sort-button" onClick={()=>setSort(v=>v==='desc'?'asc':'desc')}>参与用户 <ArrowDown size={11} className={sort==='asc'?'rotate':''}/></button></th><th>主指标变化 <CircleHelp size={11}/></th><th>负责人</th><th aria-label="操作"/></tr></thead><tbody>{visible.map(e=><tr key={e.id}><td><button className="experiment-name" onClick={()=>onOpen(e)}><strong>{e.name}</strong><span>{e.id}<i>·</i>{e.key}</span></button></td><td><ServicesBadge experiment={e}/></td><td><StatusBadge status={e.status}/></td><td><div className="traffic-cell"><div><span style={{width:`${e.traffic}%`}}/></div><span>{e.traffic}%</span></div></td><td className="number-cell">{e.participants?e.participants.toLocaleString('zh-CN'):<span className="dash">—</span>}</td><td><div className="lift-cell">{e.lift!==null?<><span className={e.significant?'positive':'neutral'}>{e.significant&&<TrendingUp size={13}/>} {e.lift>0?'+':''}{e.lift.toFixed(2)}%{e.significant&&<i/>}</span><small>{e.significant?'正向显著 · 示例':'尚无显著结论'}</small></>:<><span className="dash">—</span><small>等待实验数据</small></>}</div></td><td><span className="owner-cell"><span className={`mini-avatar ${e.type}`}>{e.owner.slice(-2,-1)}</span>{e.owner}</span></td><td><button className="row-action" onClick={()=>onOpen(e)} aria-label={`查看${e.name}`}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>
 {visible.length===0&&<div className="empty-state"><Search size={27}/><strong>没有找到匹配的实验</strong><p>调整筛选条件，或创建一个新的实验。</p><button className="btn btn-small" onClick={clearFilters}>清除筛选</button></div>}
 <div className="table-pagination"><span>显示 {filtered.length?`${(safePage-1)*size+1}–${Math.min(safePage*size,filtered.length)}`:'0'} 项，共 {filtered.length} 个实验</span><div><span className="page-size">{size} 条 / 页</span><button aria-label="上一页" disabled={safePage===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={14}/></button>{Array.from({length:pages},(_,i)=>i+1).map(n=><button key={n} className={n===safePage?'current':''} aria-label={`第 ${n} 页`} aria-current={n===safePage?'page':undefined} onClick={()=>setPage(n)}>{n}</button>)}<button aria-label="下一页" disabled={safePage===pages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={14}/></button></div></div></section>
}

function Guide({onClose}:{onClose:()=>void}){return <div className="modal-overlay" onClick={onClose}><div className="guide-modal" role="dialog" aria-modal="true" aria-labelledby="guide-title" onClick={e=>e.stopPropagation()}><button className="icon-btn guide-close" onClick={onClose} aria-label="关闭指南"><X size={20}/></button><span className="guide-icon"><BookOpen size={26}/></span><div className="eyebrow">EXP LAB PLAYBOOK</div><h2 id="guide-title">从好问题，开始好实验。</h2><p>一个可信的结论，来自完整的实验过程。</p>{[['01','先写清楚假设','明确改动、目标用户和预期改善，只选择一个主指标，并设置稳定性护栏。'],['02','让分组保持一致','先选域，再按参数边界选层。跨参数层联动放入非重叠域，前后端复用同一分组。'],['03','先验证数据，再看收益','核验曝光与 SRM（样本比例失配）。固定周期实验应等到预定周期与样本量满足后再做判断。'],['04','记录结果，沉淀知识','不显著同样有价值。停止入组后等待转化窗口成熟，记录结论与后续行动。']].map(([n,t,d])=><div className="guide-step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}<div className="info-banner"><CircleHelp size={17}/><span>此版本为本地交互原型，分流、审核与指标均为演示。完整设计说明位于项目 docs 目录。</span></div><button className="btn btn-primary" onClick={onClose}>开始探索 <ArrowRight size={16}/></button></div></div>}
